In [ ]:
!unzip IMDB_Dataset.csv.zip

Archive:  IMDB_Dataset.csv.zip
replace IMDB Dataset.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: IMDB Dataset.csv

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('/content/IMDB Dataset.csv')
dataset.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
dummies = pd.get_dummies(dataset['sentiment'])
dummies.head()

   negative  positive
0         0         1
1         0         1
2         0         1
3         1         0
4         0         1

In [ ]:
dataset['encoded_sentiment'] = pd.get_dummies(dataset['sentiment'])['positive']
dataset.head()

,review,sentiment,encoded_sentiment
0,One of the other reviewers has mentioned that ...,positive,1
1,A wonderful little production. <br /><br />The...,positive,1
2,I thought this was a wonderful way to spend ti...,positive,1
3,Basically there's a family where a little boy ...,negative,0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1

In [ ]:
z = 0
i = 0
for i in range(50000):
  if dataset['encoded_sentiment'][i]==1:
    z = z+1
    i = i+1
print(z)

25000

In [ ]:
X = dataset['review'] 
y = dataset['encoded_sentiment']

In [ ]:
# f = open(file='/content/IMDB Dataset.csv', mode='r')
# for i in encoded_sentiment:
#   y_ = 

# for line in f.readlines():
#   print(line)
#   line = line.strip()
#   line = line.split(",")
#   if 
#    y.append(int(line[-1]))
#    X.append(line[0].strip())
#  f.close()

# print(X[0])
# print(len(X))
# print(y[0])
# print(len(y))

In [ ]:
# from matplotlib import pyplot as plt
# print(X[0])
# print(len(X), len(y))
# plt.hist(y, bins=20)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, 
                                                    random_state=42)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(X)

X_seq_train = tokenizer.texts_to_sequences(X_train)
X_seq_test = tokenizer.texts_to_sequences(X_test)
print(X_seq_train)
print(X_seq_test)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
print(X_seq_train[0])
print(tokenizer.sequences_to_texts([[432, 47]]))
print(X_train[0])

[196, 48, 10, 800, 2198, 539, 300, 1, 106, 1862, 2055, 4492, 2, 825, 4999, 12, 1, 228, 1, 81, 780, 53, 50, 22, 101, 4, 1, 27, 2008, 102, 35, 25, 34, 120, 1127, 12, 9, 6, 2380, 1189, 5, 458, 48, 555, 5, 93, 33, 23, 39, 934, 407, 15, 1, 164, 5, 2956, 24, 4634, 20, 3, 2972, 12, 45, 75, 221, 72, 126, 8, 79, 3191, 195, 20, 240, 2, 1, 443, 7, 7, 10, 206, 145, 21, 62, 27, 15, 74, 367, 300, 3, 19, 18, 9, 206, 26, 302, 12, 14, 1, 116, 444, 2, 14, 1, 1637, 626, 70, 419, 381, 10, 89, 118, 48, 113, 368, 33, 36, 18, 43, 10, 13, 93, 482, 15, 3, 363, 1137, 61, 8, 1, 469, 214, 1019, 5, 4259, 8, 3, 174, 4, 34, 433, 703, 634, 12, 3780, 239, 110, 846, 36, 172, 30, 224, 196, 1, 434, 365, 55, 3582, 3, 279, 7, 7, 157, 1726, 190, 6, 1, 738, 1993, 1, 1180, 4, 3015, 3757, 1882, 2, 146, 145, 3, 226, 4, 3, 207, 326, 2, 145, 1077, 16, 88, 4, 132, 2872, 18, 10, 154, 99, 4, 1, 3898, 300, 11, 17, 989, 36, 1, 495, 492, 2592, 250, 73, 76, 106, 106, 696, 60, 85, 1057, 1343, 5, 229, 132, 23, 4201, 31, 138, 212, 1133, 14, 4511, 31, 3, 2409, 2, 8, 11, 6, 3, 448, 14, 619, 4, 1, 719, 3052, 1, 1245, 2, 73, 3596, 1, 164, 1514, 1, 1239, 5, 1674, 1, 888, 1261, 5, 1, 309, 140, 2889, 2, 410, 624, 7, 7, 1, 272, 6, 3683, 1010, 5, 26, 39, 14, 1378, 217, 65, 2, 46, 6, 30, 224, 27, 191, 1473, 8, 1088, 18, 10, 4656, 84, 1, 227, 66, 358, 68, 54, 27, 5, 3749, 15, 44, 21, 193, 5, 3, 879, 3438, 1773, 22, 25, 5, 160, 197, 176, 3, 111, 12, 1569, 472, 75, 221, 5, 327, 2, 3498, 35, 23, 51, 71, 1890, 4808, 14, 9, 1388, 11, 19, 6, 3, 3574, 2064, 16, 61, 1, 2414, 469, 533, 2, 3, 171, 2643, 2811, 1776, 5, 586, 9, 36, 1, 3933, 454, 156, 206, 352, 3944]
['lost some']
One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

In [ ]:
for i in X_seq_train[0]:
   print(f"{i} -----> {tokenizer.index_word[i]}")

196 -----> that's
48 -----> what
10 -----> i
800 -----> kept
2198 -----> asking
539 -----> myself
300 -----> during
1 -----> the
106 -----> many
1862 -----> fights
2055 -----> screaming
4492 -----> matches
2 -----> and
825 -----> general
4999 -----> mayhem
12 -----> that
1 -----> the
228 -----> minutes
1 -----> the
81 -----> also
780 -----> stand
53 -----> up
50 -----> when
22 -----> you
101 -----> think
4 -----> of
1 -----> the
27 -----> one
2008 -----> dimensional
102 -----> characters
35 -----> who
25 -----> have
34 -----> so
120 -----> little
1127 -----> depth
12 -----> that
9 -----> it
6 -----> is
2380 -----> virtually
1189 -----> impossible
5 -----> to
458 -----> care
48 -----> what
555 -----> happens
5 -----> to
93 -----> them
33 -----> they
23 -----> are
39 -----> just
934 -----> badly
407 -----> written
15 -----> for
1 -----> the
164 -----> director
5 -----> to
2956 -----> hang
24 -----> his
4634 -----> beliefs
20 -----> on
3 -----> a
2972 -----> topic
12 -----> that
45 -----> has
75 -----> been
221 -----> done
72 -----> much
126 -----> better
8 -----> in
79 -----> other
3191 -----> dramas
195 -----> both
20 -----> on
240 -----> tv
2 -----> and
1 -----> the
443 -----> cinema
7 -----> br
7 -----> br
10 -----> i
206 -----> must
145 -----> i'm
21 -----> not
62 -----> really
27 -----> one
15 -----> for
74 -----> bad
367 -----> performances
300 -----> during
3 -----> a
19 -----> film
18 -----> but
9 -----> it
206 -----> must
26 -----> be
302 -----> said
12 -----> that
14 -----> as
1 -----> the
116 -----> best
444 -----> friend
2 -----> and
14 -----> as
1 -----> the
1637 -----> nasty
626 -----> brother
70 -----> were
419 -----> absolutely
381 -----> terrible
10 -----> i
89 -----> don't
118 -----> know
48 -----> what
113 -----> acting
368 -----> school
33 -----> they
36 -----> from
18 -----> but
43 -----> if
10 -----> i
13 -----> was
93 -----> them
482 -----> i'd
15 -----> for
3 -----> a
363 -----> full
1137 -----> post
61 -----> only
8 -----> in
1 -----> the
469 -----> lead
214 -----> role
1019 -----> manages
5 -----> to
4259 -----> impress
8 -----> in
3 -----> a
174 -----> cast
4 -----> of
34 -----> so
433 -----> called
703 -----> british
634 -----> talent
12 -----> that
3780 -----> we'll
239 -----> probably
110 -----> never
846 -----> hear
36 -----> from
172 -----> again
30 -----> at
224 -----> least
196 -----> that's
1 -----> the
434 -----> hope
365 -----> next
55 -----> time
3582 -----> hire
3 -----> a
279 -----> different
7 -----> br
7 -----> br
157 -----> another
1726 -----> intriguing
190 -----> thought
6 -----> is
1 -----> the
738 -----> soundtrack
1993 -----> featuring
1 -----> the
1180 -----> likes
4 -----> of
3015 -----> snow
3757 -----> ian
1882 -----> brown
2 -----> and
146 -----> now
145 -----> i'm
3 -----> a
226 -----> bit
4 -----> of
3 -----> a
207 -----> music
326 -----> fan
2 -----> and
145 -----> i'm
1077 -----> familiar
16 -----> with
88 -----> most
4 -----> of
132 -----> these
2872 -----> artists
18 -----> but
10 -----> i
154 -----> didn't
99 -----> any
4 -----> of
1 -----> the
3898 -----> tracks
300 -----> during
11 -----> this
17 -----> movie
989 -----> apart
36 -----> from
1 -----> the
495 -----> run
492 -----> b
2592 -----> sides
250 -----> anyone
73 -----> we
76 -----> get
106 -----> many
106 -----> many
696 -----> musical
60 -----> which
85 -----> how
1057 -----> we're
1343 -----> suppose
5 -----> to
229 -----> feel
132 -----> these
23 -----> are
4201 -----> accompanied
31 -----> by
138 -----> such
212 -----> original
1133 -----> images
14 -----> as
4511 -----> couples
31 -----> by
3 -----> a
2409 -----> lake
2 -----> and
8 -----> in
11 -----> this
6 -----> is
3 -----> a
448 -----> problem
14 -----> as
619 -----> none
4 -----> of
1 -----> the
719 -----> songs
3052 -----> convey
1 -----> the
1245 -----> mood
2 -----> and
73 -----> we
3596 -----> realise
1 -----> the
164 -----> director
1514 -----> lacks
1 -----> the
1239 -----> ability
5 -----> to
1674 -----> carry
1 -----> the
888 -----> emotional
1261 -----> journey
5 -----> to
1 -----> the
309 -----> audience
140 -----> through
2889 -----> storytelling
2 -----> and
410 -----> dialogue
624 -----> alone
7 -----> br
7 -----> br
1 -----> the
272 -----> ending
6 -----> is
3683 -----> presumably
1010 -----> meant
5 -----> to
26 -----> be
39 -----> just
14 -----> as
1378 -----> everybody
217 -----> gets
65 -----> their
2 -----> and
46 -----> there
6 -----> is
30 -----> at
224 -----> least
27 -----> one
191 -----> big
1473 -----> shock
8 -----> in
1088 -----> store
18 -----> but
10 -----> i
4656 -----> remained
84 -----> because
1 -----> the
227 -----> script
66 -----> had
358 -----> given
68 -----> me
54 -----> no
27 -----> one
5 -----> to
3749 -----> root
15 -----> for
44 -----> it's
21 -----> not
193 -----> enough
5 -----> to
3 -----> a
879 -----> hot
3438 -----> button
1773 -----> issue
22 -----> you
25 -----> have
5 -----> to
160 -----> actually
197 -----> give
176 -----> us
3 -----> a
111 -----> plot
12 -----> that
1569 -----> hasn't
472 -----> already
75 -----> been
221 -----> done
5 -----> to
327 -----> death
2 -----> and
3498 -----> individuals
35 -----> who
23 -----> are
51 -----> more
71 -----> than
1890 -----> window
4808 -----> dressing
14 -----> as
9 -----> it
1388 -----> stands
11 -----> this
19 -----> film
6 -----> is
3 -----> a
3574 -----> noble
2064 -----> failure
16 -----> with
61 -----> only
1 -----> the
2414 -----> promising
469 -----> lead
533 -----> actress
2 -----> and
3 -----> a
171 -----> few
2643 -----> mildly
2811 -----> punch
1776 -----> ups
5 -----> to
586 -----> save
9 -----> it
36 -----> from
1 -----> the
3933 -----> bin
454 -----> 4
156 -----> 10
206 -----> must
352 -----> try
3944 -----> harder

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_length = max([len(t) for t in X_seq_train] + [len(t) for t in X_seq_test])
print(max_length)
X_pad_train = pad_sequences(sequences=X_seq_train, 
                              maxlen=max_length, 
                              padding='post')

print(X_pad_train.shape)

X_pad_test = pad_sequences(sequences=X_seq_test, 
                              maxlen=max_length,     
                              padding='post')
print(X_pad_test.shape)

2119
(40000, 2119)
(10000, 2119)

In [ ]:
X_pad_train[1]

array([ 10, 115,  21, ...,   0,   0,   0], dtype=int32)

In [ ]:
# ML: X_pad ->  sentiment 
from tensorflow.keras.layers import Embedding, Input, Conv1D, Flatten, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K

vocab_size = 5000
p = 0.1

inp = Input(shape=(max_length))
x = Embedding(vocab_size, 128, input_length=max_length)(inp)
x = Dropout(p)(x)
x = Conv1D(filters=32, kernel_size=1, 
           padding='same', activation='relu')(x)

x = Dropout(p)(x)
x = Conv1D(filters=16, kernel_size=1, 
           padding='same', activation='relu')(x)

# collect features: poolling??? -> inovations 
# dãn ma trận 59 x 16 -> 944-vector
#x = Flatten()(x)

# Trung bình hoá các feature của chuỗi
x = K.mean(x, keepdims=False, axis=1)

# Fully connected layer for classification
x = Dense(units=16, activation='relu')(x)
x = Dropout(p)(x)
x = Dense(units=1, activation='sigmoid')(x) # xác suất để x là positive 

model = Model(inputs=inp, outputs=x)
model.summary()

# compile model -> optimizer, loss, evaluation metrics
model.compile(loss="binary_crossentropy", optimizer='adam', metrics=['acc'])

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 2119)]            0

 embedding (Embedding)       (None, 2119, 128)         640000

 dropout (Dropout)           (None, 2119, 128)         0

 conv1d (Conv1D)             (None, 2119, 32)          4128

 dropout_1 (Dropout)         (None, 2119, 32)          0

 conv1d_1 (Conv1D)           (None, 2119, 16)          528

 tf.math.reduce_mean (TFOpLa  (None, 16)               0
 mbda)

 dense (Dense)               (None, 16)                272

 dropout_2 (Dropout)         (None, 16)                0

 dense_1 (Dense)             (None, 1)                 17

=================================================================
Total params: 644,945
Trainable params: 644,945
Non-trainable params: 0
_________________________________________________________________

In [ ]:
y = np.array(y)
model.fit(X_pad_train, np.array(y_train), epochs=10, batch_size=64, validation_data=(X_pad_test, y_test))

Epoch 1/10
625/625 [==============================] - 25s 37ms/step - loss: 0.4837 - acc: 0.7538 - val_loss: 0.2877 - val_acc: 0.8870
Epoch 2/10
625/625 [==============================] - 23s 37ms/step - loss: 0.2761 - acc: 0.8937 - val_loss: 0.2610 - val_acc: 0.8930
Epoch 3/10
625/625 [==============================] - 23s 36ms/step - loss: 0.2426 - acc: 0.9071 - val_loss: 0.2469 - val_acc: 0.8999
Epoch 4/10
625/625 [==============================] - 23s 37ms/step - loss: 0.2279 - acc: 0.9144 - val_loss: 0.2531 - val_acc: 0.8943
Epoch 5/10
625/625 [==============================] - 23s 36ms/step - loss: 0.2210 - acc: 0.9180 - val_loss: 0.2510 - val_acc: 0.8969
Epoch 6/10
625/625 [==============================] - 23s 36ms/step - loss: 0.2133 - acc: 0.9210 - val_loss: 0.2526 - val_acc: 0.8959
Epoch 7/10
625/625 [==============================] - 23s 37ms/step - loss: 0.2113 - acc: 0.9222 - val_loss: 0.2603 - val_acc: 0.8946
Epoch 8/10
625/625 [==============================] - 23s 37ms/step - loss: 0.2076 - acc: 0.9242 - val_loss: 0.2632 - val_acc: 0.8951
Epoch 9/10
625/625 [==============================] - 23s 37ms/step - loss: 0.2046 - acc: 0.9256 - val_loss: 0.2633 - val_acc: 0.8939
Epoch 10/10
625/625 [==============================] - 23s 37ms/step - loss: 0.2039 - acc: 0.9255 - val_loss: 0.2669 - val_acc: 0.8934

In [ ]:
y_pred = model.predict(X_pad_test)
y_pred[y_pred>0.5] = 1
y_pred[y_pred<=0.5] = 0

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.89      4961
           1       0.88      0.91      0.90      5039

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000

In [ ]:
def predict(seq, model):
  test_text = [seq]
  X_test = tokenizer.texts_to_sequences(test_text)
  X_test_padd = pad_sequences(sequences=X_test, maxlen=max_length, padding='post')

  p = model.predict(X_test_padd)[0, 0]

  if p > 0.5: 
    return "Positive", p
  else:
    return "Negatvie", p

seq = "It is bad movie"

predict(seq, model)

('Negatvie', 0.30797717)